packages:
  - packages/*

catalog:
  "@nuxt/kit": ^4.2.0
  "@nuxt/schema": ^4.2.0
  "rolldown": 1.0.0-beta.27
  "rollup": ^4.52.5
  "vite": ^7.1.12
  "webpack": ^5.102.1
  "magic-string": ^0.30.21
  "unplugin": ^2.3.10

catalogs:
  peer:
    "@farmfe/core": ">=1.7.11"
    "@nuxt/kit": "^4.2.0"
    "@nuxt/schema": "^4.2.0"
    "esbuild": "*"
    "rolldown": "*"
    "rollup": "^4.52.5"
    "vite": ">=7.1.12"
    "webpack": "^5.102.1"
    "vue": ">=3.5.22"
    "typescript": ">=5.9.3"

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
