packages:
  - packages/*

catalog:
  "@nuxt/kit": ^4.0.2
  "@nuxt/schema": ^4.0.2
  "rolldown": 1.0.0-beta.27
  "rollup": ^4.46.2
  "vite": ^7.0.6
  "webpack": ^5.101.0
  "magic-string": ^0.30.17
  "unplugin": ^2.3.5

catalogs:
  peer:
    "@farmfe/core": ">=1.7.10"
    "@nuxt/kit": "^4.0.2"
    "@nuxt/schema": "^4.0.2"
    "esbuild": "*"
    "rolldown": "*"
    "rollup": "^4.46.2"
    "vite": ">=7.0.6"
    "webpack": "^5.101.0"
    "vue": ">=3.5.18"
    "typescript": ">=5.9.2"

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
