packages:
  - packages/*
  - packages/*/playground

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
catalog:
  "@nuxt/kit": ^4.2.2
  "@nuxt/schema": ^4.2.2
  astro: ^5.16.6
  magic-string: ^0.30.21
  rolldown: 1.0.0-beta.51
  rollup: ^4.54.0
  unplugin: 2.3.11
  vite: 7.2.4
  webpack: ^5.104.1
catalogs:
  peer:
    "@nuxt/kit": ^4.2.2
    astro: ^5.16.6
    esbuild: "*"
    typescript: ">=5.9.3"
    vue: ">=3.5.26"
