shellEmulator: true

packages:
  - packages/*
  - packages/*/playground

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
catalog:
  "@antfu/ni": "^28.0.0"
  "@nuxt/kit": ^4.2.2
  "@nuxt/schema": ^4.2.2
  "@so1ve/eslint-config": "^3.21.0"
  "@so1ve/prettier-config": "^3.21.0"
  "@types/node": "^25.0.3"
  "@typescript/native-preview": "7.0.0-dev.20251223.1"
  "@vitejs/plugin-vue": "^6.0.3"
  "@vue-macros/better-define": "^3.1.1"
  "@vue-macros/test-utils": "^3.1.1"
  "@vue/shared": ^3.5.26
  "@vue/tsconfig": "^0.8.1"
  astro: ^5.16.6
  bumpp: "^10.3.2"
  changelogithub: "^14.0.0"
  eslint: "^9.39.2"
  magic-string: ^0.30.21
  prettier: "^3.7.4"
  rollup: ^4.54.0
  tsdown: "^0.20.0"
  unplugin: 2.3.11
  unplugin-utils: ^0.3.1
  vite: 7.2.4
  vite-plugin-inspect: "^11.3.3"
  vite-tsconfig-paths: "^6.0.3"
  vitest: "^4.0.16"
  vue: "^3.5.26"
  vue-tsc: "^3.2.1"
catalogs:
  peer:
    "@nuxt/kit": ^4.2.2
    astro: ^5.16.6
    typescript: ">=5.9.3"
    vue: ">=3.5.26"
  utils:
    defu: "^6.1.4"
  volar:
    "@volar/typescript": ~2.4.27
    "@vue/language-core": ~3.2.1
