packages:
  - packages/*

catalog:
  "@nuxt/kit": ^4.2.0
  "@nuxt/schema": ^4.2.0
  magic-string: ^0.30.21
  rolldown: 1.0.0-beta.47
  rollup: ^4.52.5
  unplugin: 2.3.10
  vite: 7.2.2
  webpack: ^5.102.1

catalogs:
  peer:
    "@farmfe/core": ">=1.7.11"
    "@nuxt/kit": ^4.2.0
    "@nuxt/schema": ^4.2.0
    esbuild: "*"
    rolldown: "*"
    rollup: ^4.52.5
    typescript: ">=5.9.3"
    vite: ">=7.1.12"
    vue: ">=3.5.22"
    webpack: ^5.102.1

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
