name: autofix.ci
on:
  push:
    branches:
      - main

  pull_request: {}

permissions:
  contents: read

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: Setup
        run: npm i -g @antfu/ni

      - name: Install
        run: ni --no-frozen-lockfile

      - name: Lint and fix
        run: nr lint:fix

      - uses: autofix-ci/action@635ffb0c9798bd160680f18fd73371e355b85f27
        with:
          commit-message: "chore: apply automatic fixes"
